### ISSUE TITLE
Method CombinePeriods(periods) fails with moment ITimePeriod

### ISSUE THREAD

**Issue by dhainautraphael** [Giannoudis/TimePeriodLibrary#9] opened 2017-04-20 15:11 UTC
The following code give 365 Days as **TotalDuration** 
but 2 Days (or maybe 2 seconds) what exepected.

I know that TimeRange is a moment (datetimes of timeRanges start and end at same moment) but it s really the expected behavior ?

```
// Combine Periods
List<TimeRange> timeRanges = new List<TimeRange>() {
    new TimeRange() { Start = new DateTime(2016, 01, 01), End = new DateTime(2016, 01, 01) },
    new TimeRange() { Start = new DateTime(2016, 12, 31), End = new DateTime(2016, 12, 31) }
};

TimePeriodCollection periods = new TimePeriodCollection(timeRanges);
TimePeriodCombiner<TimeRange> periodCombiner = new TimePeriodCombiner<TimeRange>();
ITimePeriodCollection combinedPeriods = periodCombiner.CombinePeriods(periods);
```

**Comment by Giannoudis** [comment] 2017-05-24 13:07
Many thanks for your feedback. The issue is fixed in version 2.1.0.

**Closed by Giannoudis** 2017-05-24 13:07 UTC
